# Numpy Ufunctions

### Basic Operators
Numpy的快速在於使用向量化的運算，而提供這些高速運算的func.即為Ufunctions(universal function)  
以下介紹Numpy內算術用的Ufunc: 
> array運算子 : 包含+,-,/,*,//,**,%,布林運算子,binary運算子...etc  
> 絕對值 : abs()   
> 三角函數 : sin , cos , tan , ... etc  
> 指數對數 : exp , power , log2 , log10 , log ... etc  

In [2]:
import numpy as np
x = [1,2,3]

In [5]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [6]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [8]:
np.power(10,x)

array([  10,  100, 1000], dtype=int32)

### 設定輸出
使用out arg可以讓運算結果賦值給另一個變數，類似R語言的 result -> variable  


In [14]:
# 傳出運算結果
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)

array([ 0., 10., 20., 30., 40.])

In [13]:
y

array([ 0., 10., 20., 30., 40.])

In [18]:
# 指定傳出結果的放置位置
y = np.empty(10)
np.multiply(x,10,out=y[::2]) , y

(array([ 0., 10., 20., 30., 40.]),
 array([ 0.,  0., 10.,  0., 20.,  0., 30.,  0., 40.,  0.]))

In [16]:
# 注意out接收的長度要一致，否則會報錯
#np.multiply(x,10,out=y[::2])

### 連乘積與外積
> .reduce() 可以讓前一個運算遍歷所有元素，直到沒元素並回傳結果  
> .outer() 計算成對輸出，類似九九乘法表的形式  

In [22]:
# 相當於連加 1+2+3+4+5 = 15
x = np.arange(1,6)
np.add.reduce(x)

15

In [21]:
# 也能用於連乘 1*2*3*4*5 = 5! = 120
x = np.arange(1,6)
np.multiply.reduce(x)

120

In [23]:
# 外積
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Comparison Operator
對陣列的每一個元素做指定條件的比較，運算子和對應的ufunc如下:
> `==` : np.equal()  
> `!=` : np.not_equal()  
> `<` : np.less()  
> `<=` : np.less_equal()  
> `>` : np.less_greater()  
> `>=` : np.greater_equal()  

In [3]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(f'arr =\n{arr}\n\narr2 =\n{arr2}\n')
arr2 > arr, arr2 == arr, arr2 < arr

arr =
[[1. 2. 3.]
 [4. 5. 6.]]

arr2 =
[[ 0.  4.  1.]
 [ 7.  2. 12.]]



(array([[False,  True, False],
        [ True, False,  True]]),
 array([[False, False, False],
        [False, False, False]]),
 array([[ True, False,  True],
        [False,  True, False]]))

### Boolean Operator
運算子和其等價的ufunc如下:
> `&` : np.bitwise_and  
> `|` : np.bitwise_or  
> `^` : np.bitwise_xor  
> `~` : np.bitwise_not  

In [21]:
import pandas as pd
X = np.random.randn(5,5)
X

array([[-1.16488681,  0.04296004,  1.62482742,  1.36147399,  0.13424933],
       [-2.05473431, -0.04540973, -0.06304158, -0.4835946 , -0.5697449 ],
       [-1.14117705, -0.39374707,  0.41181516,  0.45198879, -0.4303424 ],
       [ 0.46650991,  1.51997476,  0.03753472,  0.65336038, -1.15676546],
       [ 0.62971563,  0.42933432,  0.62626542, -1.10938906, -0.47857121]])

In [22]:
# 查看有多少元素在這個區間內
np.sum( (X>0.5) & (X<1.2) )

3

In [23]:
(X>0.5) & (X<1.2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [ True, False,  True, False, False]])

In [28]:
# 查看有多少有多少元素不在這個區間內
np.sum( ~(X>1.2) )

22

In [29]:
~(X>1.2)

array([[ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])